-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

local script_dir = debug.getinfo(1, "S").source:sub(2):match("(.*/)")

dofile(script_dir .. "config.lua")
dofile(script_dir .. "keybinds.lua")
dofile(script_dir .. "appearance.lua")
